### ISSUE TITLE
myComix 폴더안에 하부 폴더가 있을경우 인식을 하나요?

### ISSUE THREAD

**Issue by thestreetdj** [imueRoid/myComix#2]
지금 확인해봤는데
myComix 아래에 MANGA 라는 폴더가 있음 ...처리가 안되는걸 확인했습니다.

**Comment by imueRoid** [comment]
답변이 늦었습니다. 마이코믹스 서버의 하위폴더의 경우 절대경로를 이용해서 인식이 가능하긴 할겁니다. 다만 파일 저장위치와 서버위치를 분리해서 사용하는 것을 염두로 만들다보니 고려하지 않았네요..
